SistemaVoucher/urls.py
from django.contrib import admin
from django.urls import path, include
# importa as configurações da aplicação
from django.conf import settings
# importa as comfiguraçoes do static
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin1'),
    path('', include('login.urls')),
    path('voucher/',include('app_voucher.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_voucher/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('criar/', views.criar, name="criar"),
    path('ver/', views.ver, name="ver"),
    path('registros/', views.registros, name="registros"),
]

login/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.login, name='loginhome'),
    path('login',views.login, name='login'),
    path('cadastro',views.cadastro, name='cadastro'),
    path('logout/', views.user_logout, name='deslogar'),
]

app_voucher/models.py
from django.db import models
from django.contrib.auth.models import User
from .choices import ChoicesZona
# Create your models here.

class Especialidade(models.Model):
    nome = models.CharField(max_length=20,unique=True)
    descrição = models.CharField(max_length=30, null=True, blank=True)
    
    def __str__(self) -> str:
        return self.nome
    
class Voucher(models.Model):
    matricula = models.CharField(max_length=30)
    nomeFiliado = models.CharField(max_length=70)
    especialidade = models.ForeignKey(Especialidade, on_delete=models.DO_NOTHING)
    unidade = models.CharField(max_length=10, choices=ChoicesZona.choices)
    consultor = models.CharField(max_length=30)
    dataDaConsulta = models.CharField(max_length=10)
    dataDeGeracao = models.DateField(null=True)
    useuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    
    def __str__(self) -> str:
        return self.nomeFiliado
    

app_voucher/views.py
from django.shortcuts import render,redirect
# permição / registro
from django.contrib.auth import authenticate
from django.contrib.auth import login as login2
from django.contrib.auth.decorators import login_required
# Realizar testes
from django.http import HttpResponse
# Gerenciador de imagens, arquivos e data
'''from PIL import Image'''
import os
# importa a data e hora
from django.utils import timezone
from datetime import datetime
# importando as comfiguraçoes
from django.conf import settings
# Model
from django.db.models import Q
from .models import Voucher, Especialidade
# choices
from .models import ChoicesZona
# Model User
from django.contrib.auth.models import User
#redirecionar / ververce
from django.urls import reverse
from django.http import HttpResponseRedirect
# importe verificador
import re
# Create your views here.

@login_required(login_url="login")
def criar(request,alertstatus=""):
    '''sera responsavel por criar os vouches e arquivar eles'''
    if request.method == 'GET':
        alertstatus = request.session.get('alertstatus')
        #pega a especialidade LIMPEZA ODONTOLOGICA
        try:
            getEspecialidade = Especialidade.objects.get(nome='LIMPEZA ODONTOLOGICA')
        except:
            getEspecialidade = 'NaN'
            pass
        # pega a quantidade de voucher sem limpeza odontologica
        try:
            getUser = User.objects.get(username=request.user)
            qtd_voucher = Voucher.objects.filter(useuario__id=getUser.id)
            qtd_voucher = qtd_voucher.exclude(especialidade=getEspecialidade.id)
            contadorSemLimpeza = qtd_voucher.count()
        except:
            contadorSemLimpeza = 'NaN'
            pass
        # pega a quantidade de voucher de limpeza odontologica
        try:
            getEspecialidade = Especialidade.objects.get(nome='LIMPEZA ODONTOLOGICA')
            qtd_voucherLimpeza = Voucher.objects.filter(useuario__id=getUser.id,especialidade=getEspecialidade)
            contadorLimpeza = qtd_voucherLimpeza.count()
        except:
            contadorLimpeza = 'NaN'
            pass
        
        #pega as especialidades
        try:
            allEspecialidade = Especialidade.objects.all()
        except:
            allEspecialidade = 'NaN'
            pass
        #pega todos os usuarios
        today = timezone.now()
        allUsers = User.objects.all()
        #verifica os vouchers criados no mes
        user = request.user
        this_month_vouchers = Voucher.objects.filter(useuario=user, dataDeGeracao__month=today.month).count()
        
        if this_month_vouchers >= 10:
            status = "limite atingido"
        else:
            status = ""
        return render(request,'voucher_criar.html',{'status':status,
                                                    'alertstatus':alertstatus,
                                                    'contadorSemLimpeza':contadorSemLimpeza,
                                                    'contadorLimpeza':contadorLimpeza,
                                                    'contadorVocher':this_month_vouchers,
                                                    'allUsers':allUsers,
                                                    'allEspecialidade':allEspecialidade,
                                                    'Zonas': ChoicesZona.choices,
                                                    })
    elif request.method == 'POST':
        today = timezone.now()
        # pega a quantidade de voucher sem limpeza odontologica
        getUser = User.objects.get(username=request.user)
    
        user = request.user    
        this_month_vouchers = Voucher.objects.filter(useuario=user, dataDeGeracao__month=today.month).count()
        
        if (getUser.is_staff == True) or (this_month_vouchers <= 9):
            #pegando nome e sobrenome de quem esta logado
            nomeL = request.user.first_name
            sobrenomeL = request.user.last_name
            #pegando as informaçãoes dos usuarios
            matricula = request.POST.get("matricula")

                
            nomeFiliado = request.POST.get("nomeFiliado")
            
            getEspecialidade = request.POST.get("especialidade")
            especialidade = Especialidade.objects.get(nome=getEspecialidade)
            especialidade = Especialidade.objects.get(id=especialidade.id)
            unidade = request.POST.get("unidade")

            getConsultor = request.POST.get("consultor")

            if (getConsultor == "") or (getConsultor == None):
                consultor = str(nomeL+' '+sobrenomeL)
                userr = User.objects.get(username=request.user)
            else:
                consultor = getConsultor
                userr = User.objects.get(username=consultor)
                consultor = str(userr.first_name+' '+userr.last_name)
                

            
            dataDaConsulta = request.POST.get("dataDaConsulta")
            dataFormatada = datetime.strptime(dataDaConsulta,"%Y-%m-%d")
            dataDaConsulta = datetime.strftime(dataFormatada,"%d/%m/%Y")
            
            dataDeGeracao = today.date()
            
            padrao = r'AM3480\d+'
            if not re.search(padrao,matricula):
                if 'alertstatus' in request.session:
                    status = ""
                    alertstatus = request.session['alertstatus'] = status
                try:
                    #instanciando e guardando no banco de dados
                    voucher = Voucher(
                                    matricula=matricula,
                                    nomeFiliado=nomeFiliado,
                                    especialidade=especialidade,
                                    unidade=unidade,
                                    consultor=consultor,
                                    dataDaConsulta=dataDaConsulta,
                                    dataDeGeracao=dataDeGeracao,
                                    useuario_id=userr.id
                                    )
                    voucher.save()
                    status = 'sucesso'
                except:
                    status = 'error'
            else:
                status = 'A matricula pertence a outra unidade!'
                alertstatus = request.session['alertstatus'] = status
                return redirect('criar')
            
            alertstatus = request.session['alertstatus'] = ''
            unidade = dict(ChoicesZona.choices).get(voucher.unidade, "Desconhecido")
            
            return render(request,'voucher_ver.html',{'status':status,
                                                    'matricula':matricula,
                                                    'nomeFiliado':nomeFiliado,
                                                    'especialidade':especialidade,
                                                    'unidade':unidade,
                                                    'consultor':consultor,
                                                    'dataDaConsulta':dataDaConsulta,
                                                    'dataDeGeracao':dataDeGeracao,
                                                    })
        else:
            return redirect("registros")
        
'''
        #traser tudo do banco
        voucher = Voucher.objects.all()
        #caso queira filtrar
        voucher = Voucher.objects.filter(nomeFiliado="n")
        #validaçao para ver se ja existe no banco de dados
        voucher = Voucher.objects.filter(nomeFiliado="n")
        if voucher.exists():
            pass # se ja existir usuario vai cair aqui
        else:
            pass # se não existir vai cair aqui
        
'''
@login_required(login_url="login")
def ver(request):
    '''ele sera a parte de visualização dos vouches'''
    if request.method == 'POST':
    # usa o proprio horario do django o pradrao e: (07 de abril de 2023)
        # tipos de formatação de hora  data
            # dd/mm/yyyy
      #  formatted_date = data_atual.strftime('%d/%m/%Y')
            # hh:mm:ss
      #  formatted_time = data_atual.strftime('%H:%M:%S')
            # yyyy
      #  week_of_year = data_atual.strftime('%Y')
        '''inicializando codigo'''
        # data_atual = timezone.now()
        try:
            href_id = request.POST.get('voucher')
            voucher = Voucher.objects.filter(id=href_id)
            for voucher1 in voucher:
                matricula = voucher1.matricula
                nomeFiliado = voucher1.nomeFiliado
                especialidade = voucher1.especialidade
                unidade = dict(ChoicesZona.choices).get(voucher1.unidade, "Desconhecido")
                dataDaConsulta = voucher1.dataDaConsulta
                consultor = voucher1.consultor
                dataDeGeracao = voucher1.dataDeGeracao
            
            # visualizar voucher
            return render(request, 'voucher_ver.html', {
                                                        'matricula':matricula,
                                                        'nomeFiliado':nomeFiliado,
                                                        'especialidade':especialidade,
                                                        'unidade':unidade,
                                                        'dataDaConsulta':dataDaConsulta,
                                                        'consultor':consultor,
                                                        'dataDeGeracao':dataDeGeracao
                                                        })
        except:
            matricula = ''
            nomeFiliado = ''
            especialidade = ''
            unidade = ''
            dataDaConsulta = ''
            consultor = ''
            dataDeGeracao = ''
            return render(request, 'voucher_ver.html', {
                                                        'matricula':matricula,

app_voucher/templates/voucher_criar.html
{% extends "base.html" %}

{% block title %}
Criar
{% endblock %}

{% block navItem %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  Quantidade de Vouchers
  </a>
  <ul class="dropdown-menu">
  <li><a class="dropdown-item" href="{% url 'criar' %}">Vouchers Criados: {{contadorVocher}}</a></li>
  <li><a class="dropdown-item" href="{% url 'criar' %}">Vouchers de Limpeza: {{contadorLimpeza}} | limite = 3</a></li>
  <li><a class="dropdown-item" href="{% url 'criar' %}">Vouchers Normal: {{contadorSemLimpeza}} | limite = 10</a></li>
  </ul>
</li>
{% endblock %}

{% block main %}
    <div class="justify-content-center m-auto mt-5 w-50">
      <form action="{% url 'criar' %}" method="POST"> {% csrf_token %}
        <div class="div-campo">
          <label class="exampleFormControlInput1">MATRÍCULA:</label>
          <input class="form-control" type="text" name="matricula" placeholder='AM3120XXXXXX' required>
        </div>
        <div class="div-campo">
          <label>NOME:</label>
          <input class="form-control" type="text" name="nomeFiliado" required>
        </div>
        <div class="div-campo">
          <label>ESPECIALIDADE:</label>
          <select class="form-select" aria-label="Default select example" name="especialidade" required>
            <option value='' selected>Selecione</option>
            {% for especialidade in allEspecialidade %}
                <option>{{ especialidade }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="div-campo">
          <label>UNIDADE:</label>
          <select class="form-select" aria-label="Default select example" name="unidade" required>
            <option selected>Selecione</option>
            {% for value, label in Zonas %}
                <option value="{{ value }}">{{ label }}</option>
            {% endfor %}
          </select>
        </div>

        <div class="div-campo">
          <label>DATA DA CONSULTA:</label>
          <input class="form-control" type="date" name="dataDaConsulta" placeholder="DD/MM/YYYY" required>
        </div>

        {% if user.is_staff %}
        <div class="div-campo">
          <label>CONSULTOR:</label>
          <!--<input class="form-control" type="text" name="consultor">-->
          <select class="form-select" aria-label="Default select example" name="consultor">
            <option value="" selected>Selecione</option>
            {% for user in allUsers %}
                <option>{{user}}</option>
            {% endfor %}
          </select>
        </div>
        {% endif %}

        <div class='btn-group mt-2'>
          <button class="btn btn-success" type="submit">Criar</button>
        </div>
        <div class="div-btn">
          {% if not user.is_staff %}
          <span>{{status}}</span>
          {% endif %}
          <span>{{alertstatus}}</span>
        </div>
      </form>
    </div>
{% endblock %}

app_voucher/templates/voucher_registros.html
{% extends "base.html" %}

{% block title %}
Registros
{% endblock %}

{% block main %}
<body>
    <table class="table table-striped">
        <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Matricula</th>
              <th scope="col">Nome Filiado</th>
              <th scope="col">Especialidade</th>
              <th scope="col">Unidade</th>
              <th scope="col">Consultor</th>
              <th scope="col">Data Da Consulta</th>
              <th scope="col">Data da Criação</th>
              {% if user.is_staff %}
              <th scope="col">
                <form class="d-flex" role="search" action="{% url 'registros' %}" method="POST"> {% csrf_token %}
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="pesquisa">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
            {% for voucher in vouchers%}
            <tr>
              <th scope="row">{{voucher.id}}</th>
              <td>{{voucher.matricula}}</td>
              <td>{{voucher.nomeFiliado}}</td>
              <td>{{voucher.especialidade}}</td>
              <td>{{voucher.get_unidade_display|title}}</td>
              <td>{{voucher.consultor}}</td>
              <td>{{voucher.dataDaConsulta}}</td>
              <td>{{voucher.dataDeGeracao|date:"d/m/Y"}}</td>
              <td>
                <div class="btn-group" role="group" aria-label="Basic mixed styles example">
                  <form action="{% url 'ver' %}" method="POST"> {% csrf_token %}
                    <input type="hidden" name="voucher" value="{{voucher.id}}">
                    <input value="Ver" type="submit" class="btn btn-success">
                  </form>
                  
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
    </table>
    <!-- pagination end -->
    <div class="d-flex justify-content-center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Previous">
                  <span aria-hidden="true">&laquo;</span>
                </a>
              </li>
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            </ul>
          </nav>
    </div>
</body>
{% endblock %}

app_voucher/templates/voucher_ver.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <link rel="stylesheet" type="text/css" href="{% static 'app_voucher/css/voucher_normal.css' %}">
{% endblock %}
{% block title %}
Ver
{% endblock %}

{% block mainDiv %}
  <body>

    <div class="voucher">
      <div class="cabeçalho">
        <img class="imgvoucher" src="{% static 'app_voucher/img/voucher.png' %}">
        <h1 class="titulo">Consulta Médica</h1>
      </div>

      <div class="form">
        <img class="img_fundo" src="{% static 'app_voucher/img/fundo.png' %}" alt="">
        <div class="form1">
            <p>MATRÍCULA: <span>{{matricula|upper}}</span></p>
            <p>ESPECIALIDADE: <span>{{especialidade|upper}}</span></p>
            <p>DATA DA CONSULTA: <span>{{dataDaConsulta}}</span></p>
            <p>CONSULTOR: <span>{{consultor|upper}}</span></p>
        </div>
          <div class="form2">
            <p>NOME: <span>{{nomeFiliado|upper}}</span></p>
            <p>UNIDADE (Amor Saúde): <span>{{unidade|upper}}</span></p>
          </div>
        </div>
          <br>
        <div class="Assinatura">
          <img class="img_assinatura" src="{% static 'app_voucher/img/assinatura.png' %}" alt="">
          <p>AUTORIZADO POR: ___________________________________    &nbsp;&nbsp; DATA: {{dataDeGeracao|date:"d/m/Y"}}</p> 
        </div>
    </div>
  </body>

{% endblock %}